# Generated by Django 2.1.7 on 2019-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Key')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Settings Values')),
                ('field', models.TextField(blank=True, null=True, verbose_name='Fields')),
                ('active', models.IntegerField(blank=True, choices=[(0, 'No Active'), (1, 'Active')], default=0, null=True, verbose_name='Status Active')),
            ],
        ),
    ]
