# Generated by Django 2.1.7 on 2019-05-15 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('reference', '0002_auto_20190515_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address_id', models.IntegerField(blank=True, null=True, verbose_name='Shipping Address ID')),
                ('billing_address_id', models.IntegerField(blank=True, null=True, verbose_name='Billing Address ID')),
                ('billing_company_id', models.IntegerField(blank=True, null=True, verbose_name='Billing Company ID')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('shipping_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping No')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice No')),
                ('invoice_date', models.DateTimeField(verbose_name='Invoice Date')),
                ('delivery_date', models.DateTimeField(verbose_name='Delivery Date')),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total Discount')),
                ('total_discount_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total Discount Tax')),
                ('total_shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total Shipping')),
                ('total_shipping_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total Shipping Tax')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total')),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=13, verbose_name='Total Tax')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Carrier')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Price')),
                ('price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Price with Tax')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('notification', models.IntegerField(default=1, verbose_name='Notifications')),
            ],
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
