# Generated by Django 2.1.7 on 2019-05-15 07:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0002_auto_20190515_0646'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeProductValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attribute.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributeset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attribute.AttributeSet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=13, verbose_name='Price')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attribute.AttributeSet')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Name')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SpesificPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=13, verbose_name='Reduction')),
                ('discount_type', models.CharField(choices=[(0, 'Ammount'), (1, 'Percent')], default=0, max_length=1, verbose_name='Discount Type')),
                ('start_date', models.DateTimeField(auto_now=True, verbose_name='Start Date')),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.ProductGroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reference.Tax'),
        ),
        migrations.AddField(
            model_name='attributeproductvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product'),
        ),
    ]
